spring:
  application:
    name: order-invoice-service
  cloud:
    openfeign:
      oauth2:
        enabled: true
  # config:
  #   import: optional:configserver:http://localhost:8888
server:
  port: 8086

rsa:
  public-key: certs/public.pem